### ISSUE TITLE
running on ROS2 Humble

### ISSUE THREAD

**Issue by hwlim84** [DaniGarciaLopez/ros2_explorer#8]

**Comment by DaniGarciaLopez** [comment]
Hi! The log you're attaching is not giving enough information. I recommend you to run the launch file in debug mode to see the traceback:
```
ros2 launch -d explorer_bringup map10.launch.py
```
I assume that the problem will be mostly caused because of the rename of Nav2 Recovery Server in Humble. Check [this issue](https://github.com/DaniGarciaLopez/ros2_explorer/issues/5) for more info.
